#!/usr/bin/env bash
# Generate .env with random secrets for state encryption and optional MySQL.
#
# Usage:
#   ./generate-env.sh              # Interactive (prompts for MySQL)
#   ./generate-env.sh --mysql      # Non-interactive, include MySQL password
#   ./generate-env.sh --no-mysql   # Non-interactive, skip MySQL password
#   ./generate-env.sh --force ...  # Overwrite existing .env (requires confirmation)
set -euo pipefail

ENV_FILE=".env"
force=false
mysql_flag=""

for arg in "$@"; do
    case "$arg" in
        --mysql)    mysql_flag="yes" ;;
        --no-mysql) mysql_flag="no" ;;
        --force)    force=true ;;
        *) echo "Unknown option: $arg"; exit 1 ;;
    esac
done

# Safety: never silently overwrite
if [ -f "$ENV_FILE" ]; then
    if [ "$force" = true ]; then
        # Even with --force, back up first
        backup="${ENV_FILE}.bak.$(date +%s)"
        cp "$ENV_FILE" "$backup"
        echo "Backed up existing .env to $backup"
    else
        echo ".env already exists. To regenerate:"
        echo "  ./generate-env.sh --force          # backs up existing, then overwrites"
        echo "  ./generate-env.sh --force --mysql   # same, with MySQL password"
        exit 1
    fi
fi

passphrase=$(openssl rand -base64 32)

if [ -z "$mysql_flag" ]; then
    read -rp "Will you enable MySQL? (generates a random admin password) [y/N] " mysql_flag
fi

cat > "$ENV_FILE" <<EOF
# Generated by: ./generate-env.sh
# Date: $(date -u +%Y-%m-%dT%H:%M:%SZ)

# State encryption passphrase (min 16 chars)
# Encrypts terraform state/plan files at rest.
TF_VAR_state_passphrase="$passphrase"
EOF

if [[ "$mysql_flag" =~ ^[Yy](es)?$ ]]; then
    # Generate a MySQL-compatible password: mixed case + digits + special char
    # OCI requires: 8-32 chars, uppercase, lowercase, number, special char
    mysql_password="$(openssl rand -base64 18 | tr -d '/+=' | head -c 20)$(echo '!@#^&' | fold -w1 | shuf | head -1)$(openssl rand -hex 1 | tr '[:lower:]' '[:upper:]')"
    cat >> "$ENV_FILE" <<EOF

# MySQL admin password (8-32 chars, uppercase + lowercase + number + special)
TF_VAR_mysql_admin_password="$mysql_password"
EOF
fi

chmod 600 "$ENV_FILE"

echo
echo "Wrote $ENV_FILE (mode 600):"
echo "  - State encryption passphrase: generated"
if [[ "$mysql_flag" =~ ^[Yy](es)?$ ]]; then
    echo "  - MySQL admin password: generated"
fi
echo
echo "Back up this file — losing the passphrase means losing access to your state."
