# OCI Always Free Tier — Task Runner
# Usage: just <recipe>   (install: brew install just)

set dotenv-load

env := "terraform/environments/oci-prod"

# List available recipes
default:
    @just --list

# Auto-discover OCI config and generate oci-prod.auto.tfvars
setup:
    #!/usr/bin/env bash
    set -euo pipefail

    echo "=== OCI Free Tier Setup ==="
    echo

    # Check prerequisites
    if ! command -v oci &>/dev/null; then
        echo "Error: oci CLI not found. Install with: brew install oci-cli"
        exit 1
    fi
    if [ ! -f ~/.oci/config ]; then
        echo "Error: ~/.oci/config not found. Run: oci setup config"
        exit 1
    fi

    # Parse ~/.oci/config DEFAULT profile
    tenancy=$(awk '/^\[DEFAULT\]/,/^\[/' ~/.oci/config | grep '^tenancy' | head -1 | cut -d= -f2 | tr -d ' ')
    user=$(awk '/^\[DEFAULT\]/,/^\[/' ~/.oci/config | grep '^user' | head -1 | cut -d= -f2 | tr -d ' ')
    region=$(awk '/^\[DEFAULT\]/,/^\[/' ~/.oci/config | grep '^region' | head -1 | cut -d= -f2 | tr -d ' ')

    if [ -z "$tenancy" ] || [ -z "$user" ]; then
        echo "Error: could not parse tenancy/user from ~/.oci/config [DEFAULT]"
        exit 1
    fi

    echo "Tenancy: $tenancy"
    echo "User:    $user"
    echo "Region:  $region"

    # Query availability domain
    echo
    echo "Querying availability domain..."
    ad=$(oci iam availability-domain list --query 'data[0].name' --raw-output 2>/dev/null) || {
        echo "Error: failed to query availability domains. Check your OCI CLI config."
        exit 1
    }
    echo "AD:      $ad"

    # Find SSH public key
    ssh_key=""
    for key_file in ~/.ssh/id_ed25519.pub ~/.ssh/id_rsa.pub ~/.ssh/id_ecdsa.pub; do
        if [ -f "$key_file" ]; then
            ssh_key=$(cat "$key_file")
            echo "SSH key: $key_file"
            break
        fi
    done
    if [ -z "$ssh_key" ]; then
        echo "Warning: no SSH public key found in ~/.ssh/"
        echo "Generate one with: ssh-keygen -t ed25519"
    fi

    # Prompt for alert email (optional)
    echo
    read -rp "Alert email for budget/monitoring notifications (optional, press Enter to skip): " alert_email

    # Write tfvars
    tfvars="{{env}}/oci-prod.auto.tfvars"
    if [ -f "$tfvars" ]; then
        echo
        read -rp "$tfvars already exists. Overwrite? [y/N] " confirm
        if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
            echo "Aborted."
            exit 0
        fi
    fi

    cat > "$tfvars" <<EOF
    # Generated by: just setup
    # Date: $(date -u +%Y-%m-%dT%H:%M:%SZ)

    compartment_ocid    = "$tenancy"
    user_ocid           = "$user"
    availability_domain = "$ad"
    ssh_public_key      = "$ssh_key"
    EOF

    # Add optional alert_email
    if [ -n "$alert_email" ]; then
        echo "alert_email         = \"$alert_email\"" >> "$tfvars"
    fi

    # Remove leading whitespace from heredoc
    sed -i.bak 's/^    //' "$tfvars" && rm -f "$tfvars.bak"

    echo
    echo "Wrote $tfvars"
    echo
    echo "Next steps:"
    echo "  1. just init"
    echo "  2. just plan"
    echo "  3. just apply"
    echo
    echo "Optional modules (add to $tfvars):"
    echo "  enable_mysql          = true   # MySQL HeatWave (run: ./generate-env.sh --force --mysql)"
    echo "  enable_object_storage = true   # S3-compatible Object Storage"

# Show your current public IP
my-ip:
    #!/usr/bin/env bash
    set -euo pipefail
    ip=$(curl -4 -s --max-time 5 https://ifconfig.me || curl -4 -s --max-time 5 https://api.ipify.org || curl -4 -s --max-time 5 https://icanhazip.com)
    echo "$ip"

# Allow SSH from your current IP and apply the change
ssh-allow:
    #!/usr/bin/env bash
    set -euo pipefail
    ip=$(curl -4 -s --max-time 5 https://ifconfig.me || curl -4 -s --max-time 5 https://api.ipify.org || curl -4 -s --max-time 5 https://icanhazip.com)
    if [ -z "$ip" ]; then
        echo "Error: could not determine public IP"
        exit 1
    fi
    cidr="${ip}/32"
    echo "Setting SSH access to: $cidr"
    tofu -chdir={{env}} apply -var="ssh_source_cidr=$cidr" -target=module.network.oci_core_security_list.main

# Revoke SSH access (close port 22)
ssh-revoke:
    tofu -chdir={{env}} apply -var="ssh_source_cidr=" -target=module.network.oci_core_security_list.main

# Run arbitrary tofu subcommands (e.g. just tofu state list)
tofu *args:
    tofu -chdir={{env}} {{args}}

# Initialize OpenTofu providers and modules
init:
    tofu -chdir={{env}} init

# Validate configuration syntax
validate:
    tofu -chdir={{env}} validate

# Format all .tf files
fmt:
    tofu fmt -recursive terraform/

# Check formatting (CI-friendly)
fmt-check:
    tofu fmt -check -recursive terraform/

# Preview infrastructure changes
plan:
    tofu -chdir={{env}} plan

# Deploy infrastructure
apply *flags:
    tofu -chdir={{env}} apply {{flags}}

# Deploy infrastructure (skip confirmation prompt)
apply-auto:
    tofu -chdir={{env}} apply -auto-approve

# Tear down infrastructure
destroy *flags:
    tofu -chdir={{env}} destroy {{flags}}

# Tear down infrastructure (skip confirmation prompt)
destroy-auto:
    tofu -chdir={{env}} destroy -auto-approve

# Show all outputs
output:
    tofu -chdir={{env}} output

# SSH to the instance
ssh:
    #!/usr/bin/env bash
    set -euo pipefail
    ip=$(tofu -chdir={{env}} output -raw instance_ip 2>/dev/null) || {
        echo "Error: could not get instance IP. Has infrastructure been deployed?"
        exit 1
    }
    exec ssh "ubuntu@$ip"

# Write S3 credentials from terraform output to .env (values never shown)
s3-creds-to-env:
    #!/usr/bin/env bash
    set -euo pipefail
    if [ ! -f .env ]; then
        echo "Error: .env not found. Run ./generate-env.sh first."
        exit 1
    fi
    # Check if already present
    if grep -q '^AWS_ACCESS_KEY_ID=' .env 2>/dev/null; then
        echo "S3 credentials already exist in .env — skipping."
        echo "To regenerate, remove the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY lines from .env first."
        exit 0
    fi
    ACCESS_KEY=$(tofu -chdir={{env}} output -raw s3_access_key 2>/dev/null) || {
        echo "Error: could not read s3_access_key from terraform output."
        echo "Make sure enable_object_storage = true and infrastructure is deployed."
        exit 1
    }
    SECRET_KEY=$(tofu -chdir={{env}} output -raw s3_secret_key 2>/dev/null) || {
        echo "Error: could not read s3_secret_key from terraform output."
        exit 1
    }
    if [ -z "$ACCESS_KEY" ] || [ "$ACCESS_KEY" = "null" ]; then
        echo "Error: S3 credentials not found. Is enable_object_storage = true?"
        exit 1
    fi
    {
        echo ""
        echo "# S3-compatible Object Storage credentials (for remote state backend)"
        echo "AWS_ACCESS_KEY_ID=\"$ACCESS_KEY\""
        echo "AWS_SECRET_ACCESS_KEY=\"$SECRET_KEY\""
    } >> .env
    echo "S3 credentials written to .env (access key and secret key)."

# Open SSH tunnel for MySQL access (localhost:3306 → MySQL)
mysql-tunnel:
    #!/usr/bin/env bash
    set -euo pipefail
    mysql_ip=$(tofu -chdir={{env}} output -raw mysql_ip_address 2>/dev/null) || {
        echo "Error: MySQL is not enabled. Set enable_mysql = true in your tfvars."
        exit 1
    }
    if [ -z "$mysql_ip" ] || [ "$mysql_ip" = "null" ]; then
        echo "Error: MySQL is not enabled. Set enable_mysql = true in your tfvars."
        exit 1
    fi
    instance_ip=$(tofu -chdir={{env}} output -raw instance_ip 2>/dev/null) || {
        echo "Error: could not get instance IP."
        exit 1
    }
    echo "MySQL tunnel: localhost:3306 → $mysql_ip:3306 via $instance_ip"
    echo "Connect with: mysql -h 127.0.0.1 -P 3306 -u admin -p"
    exec ssh -N -L "3306:$mysql_ip:3306" "ubuntu@$instance_ip"
